name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  pull_request:
    branches:
      - test_branch
jobs:
  runs-on: ubuntu-latest
  steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Setup python
       run: echo "i should see this"
	
